#!/usr/bin/env bash
file=$1
w=$2
h=$3
x=$4
y=$5

filetype=$(file -Lb --mime-type "$file")

case $filetype in
	image*)
		kitty +kitten icat --silent --stdin no --transfer-mode file --place "${w}x${h}@${x}x${y}" "$file" < /dev/null > /dev/tty
		exit 1;;
	video*)
		kitty +kitten icat --silent --stdin no --transfer-mode file --place "${w}x${h}@${x}x${y}" "$(vidthumb "$file")" < /dev/null > /dev/tty
		exit 1;;
	application/pdf)
		pdftotext $file -
		exit 1;;
esac

theme=$(case "${file##*.}" in
	rs)
		echo "rose-pine";;
	kt)
		echo "Dracula";;
	hs)
		echo "tokyonight";;
	*)
		echo "catppuccin";;
esac)

bat --color always --style="numbers" --theme "$theme" "$file"
